//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bismillah
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_dukcapil_data
    {
        public int m_dukcapil_data_id { get; set; }
        public long NIK { get; set; }
        public string name { get; set; }
        public string maiden_name { get; set; }
        public System.DateTime birth_date { get; set; }
        public string gender { get; set; }
        public int religion_id { get; set; }
        public int martial_status { get; set; }
    }
}
